### ISSUE TITLE
Icons missing due to font awesome not loading

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-academy#1]
The site uses font awesome for icons but these are not loading, eg:

![Screenshot from 2023-03-01 15-54-41](https://user-images.githubusercontent.com/2064938/222033329-d750b469-eb8d-487f-88fa-d510492a20c6.png)
![Screenshot from 2023-03-01 15-54-52](https://user-images.githubusercontent.com/2064938/222033431-4a5709a0-64df-4385-ab72-9ce218bc3c34.png)

This is due to a CORS error trying to download the font:

![Screenshot from 2023-03-01 15-53-04](https://user-images.githubusercontent.com/2064938/222033218-f2845656-14b5-4ed5-897c-21d7c1b325f1.png)

**Comment by nsitaula** [comment]
@garethbowen not sure what the issue may be but the fonts seems to load fine for me.

**Comment by garethbowen** [comment]
@nsitaula It's now working for me too. Not sure what changed, but maybe it was a temporary but in the platform? Closing as resolved.
