### ISSUE TITLE
The favicon is tiny!

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-academy#2]
It's too small to really be able to understand what it is. Replace it with the same one used on the docs/forum site.

![Screenshot from 2023-03-01 15-52-22](https://user-images.githubusercontent.com/2064938/222033552-3d5e854b-89a1-4afb-b39e-86f196f93be2.png)

**Comment by nsitaula** [comment]
@garethbowen I have updated the size of the favicon https://academy.communityhealthtoolkit.org/courses/course-v1:cht-academy+101+2022/course/

**Comment by garethbowen** [comment]
Perfect, thanks!
