### ISSUE TITLE
cht-academy: 201: CHT conf installation npm package url points to medic-conf which is deprecated

### ISSUE THREAD

**Issue by ronna** [medic/cht-academy#3]
On https://academy.communityhealthtoolkit.org/courses/course-v1:cht-academy+201+2022/courseware/cb745e0a8eb64a7da064de96e31f788a/64367310b83241d8a66e84d1f29071fc/?activate_block_id=block-v1%3Acht-academy%2B201%2B2022%2Btype%40sequential%2Bblock%4064367310b83241d8a66e84d1f29071fc

[https://www.npmjs.com/package/cht-conf](https://www.npmjs.com/package/medic-conf) is hyperlinked to  https://www.npmjs.com/package/medic-conf which is deprecated

**Comment by nsitaula** [comment]
Hi @ronna thank you for letting us know and sorry for the late response. I have updated and fixed the issue.
