### ISSUE TITLE
French translation doesn't appear to work

### ISSUE THREAD

**Issue by garethbowen** [medic/cht-academy#4]
If I select "Français" from the dropdown the page refreshes but the content is still in English.

![image](https://user-images.githubusercontent.com/2064938/229685534-990abf5d-4f35-410e-9581-42634c7e5da0.png)

**Comment by nsitaula** [comment]
Hi @garethbowen , sorry for the late response. Not sure what the issue might be. It seems to work for me. It seems sometime it takes time to load the language translations.
<img width="1396" alt="Screenshot 2023-05-16 at 8 09 05 PM" src="https://github.com/medic/cht-academy/assets/17185028/f137943b-08ea-4bdf-b29b-d22f1dfa70ce">

**Comment by garethbowen** [comment]
I'm seeing some change so technically it's probably working, but maybe needs a lot more translation...
